export const GET_POKEMON_LIST = "GET_POKEMON_LIST";
export const GET_SINGLE_POKEMON = "GET_SINGLE_POKEMON";
export const SINGLE_POKEMON_SUCCESS = "SINGLE_POKEMON_SUCCESS";
export const SEARCH_SINGLE_POKEMON = "SEARCH_SINGLE_POKEMON";
